### PR TITLE
Split Window and Ace Themes

### PR DESCRIPTION
**Pull request by TheKiteEatingTree**
This pull request gets rid of the theme preference and instead creates windowTheme and aceTheme preferences.  It addresses #460 and fixes number #496.  I do not have a windows machine so this is completely untested in windows.  I did test the chrome and native apps in os x and linux.

### CODE REVIEW

**Comment by zefhemel** [comment]
I really like this and it seems to work well. The only problem I have with this is exposing the "Ace" name to the user like that. We're not ashamed of using Ace or anything, it's just -- should the user know what Ace is? I would prefer windowTheme vs editorTheme or something. Obviously, this would involve replacing ace everywhere with editor...

What do you think?

**Comment by TheKiteEatingTree** [comment]
Yea you're definitely right.  Any user who hasn't looked at the code isn't going to know what ace is.  I'll change it to editorTheme.  Shouldn't take too much time.

**Comment by TheKiteEatingTree** [comment]
I finished renaming everything last night.  Should be good to go.  Actually caught some find/replace errors I made the first time and ended up testing all of the editor themes.

**Comment by zefhemel** [comment]
Excellent!

**Pull request merged**
