### PR TITLE
Use double quotes for all json, add .zedstate to gitignore

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Signed-off-by: Ryan Roadside ryan@roadsidemultimedia.com

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
I know leaving out the double quotes doesn't break anything, but this looks so much better:

BEFORE:
screen shot 2015-12-02 at 9 20 03 am

AFTER:
screen shot 2015-12-02 at 9 20 34 am

**Comment by zefhemel** [comment]
I think this is a matter of taste :smile: The format used is JSON5, not JSON (JSON5 allows unquoted JSON among other things like comments). We used JSON before, but JSON5 feels cleaner. Most of the modes, themes etc. have been migrated to JSON5, so this PR only touches about 1% of all the JSON in the system.

**Comment by ryanpcmcquen** [comment]
Well in that case, I'll just rebase this to add `.zedstate` to the `.gitignore`. I agree that it looks better without quotes overall, hopefully :octocat: will update his syntax highlighting. :wink:

**Comment by ryanpcmcquen** [comment]
Actually, I see now that you have the wildcard (`.*`) for hidden files in there. Nevermind!

**Pull request closed without merging**
